services:
  auth-db:
    image: postgres:15-alpine
    container_name: auth-db-container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=102030
      - POSTGRES_DB=authBanco
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d authBanco"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth-server:
    build: .
    container_name: auth-server-container
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth-db:5432/authBanco
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=102030
    depends_on:
      auth-db:
        condition: service_healthy
    restart: on-failure

volumes:
  postgres_data: